openapi: 3.0.3
info:
  title: HealTrack API
  version: 1.0.0
  description: API for HealTrack mobile app
paths:
  /appointments/:
    get:
      operationId: appointments_retrieve
      tags:
      - appointments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
          description: ''
    post:
      operationId: appointments_create
      tags:
      - appointments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Appointment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Appointment'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
          description: ''
  /appointments/{id}/:
    get:
      operationId: appointments_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - appointments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
          description: ''
    put:
      operationId: appointments_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - appointments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Appointment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Appointment'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
          description: ''
    delete:
      operationId: appointments_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - appointments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /doctors/:
    get:
      operationId: doctors_list
      tags:
      - doctors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doctor'
          description: ''
    post:
      operationId: doctors_create
      tags:
      - doctors
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Doctor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Doctor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Doctor'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
          description: ''
  /doctors/{id}/:
    get:
      operationId: doctors_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - doctors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
          description: ''
    put:
      operationId: doctors_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - doctors
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Doctor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Doctor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Doctor'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
          description: ''
    delete:
      operationId: doctors_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - doctors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /medications/:
    get:
      operationId: medications_retrieve
      tags:
      - medications
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medication'
          description: ''
    post:
      operationId: medications_create
      tags:
      - medications
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medication'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Medication'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Medication'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medication'
          description: ''
  /medications/{id}/:
    get:
      operationId: medications_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - medications
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medication'
          description: ''
    put:
      operationId: medications_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - medications
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medication'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Medication'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Medication'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medication'
          description: ''
    delete:
      operationId: medications_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - medications
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /patients/:
    get:
      operationId: patients_retrieve
      tags:
      - patients
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
    post:
      operationId: patients_create
      tags:
      - patients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
  /patients/{id}/:
    get:
      operationId: patients_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - patients
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
    put:
      operationId: patients_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - patients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
    delete:
      operationId: patients_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - patients
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        appointment_date:
          type: string
          format: date-time
        reason:
          type: string
        location:
          type: string
          nullable: true
          maxLength: 255
        type:
          $ref: '#/components/schemas/TypeEnum'
        state:
          $ref: '#/components/schemas/StateEnum'
        patient:
          type: integer
        doctor:
          type: integer
      required:
      - appointment_date
      - doctor
      - id
      - patient
      - reason
      - type
    Doctor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        surname:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        phoneNumber:
          type: string
          maxLength: 15
        dateOfBirth:
          type: string
          format: date
        specialization:
          type: string
          maxLength: 100
      required:
      - dateOfBirth
      - email
      - id
      - name
      - phoneNumber
      - specialization
      - surname
    Medication:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        dosage:
          type: string
          maxLength: 100
        patient:
          type: integer
      required:
      - dosage
      - id
      - name
      - patient
    Patient:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        surname:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        phoneNumber:
          type: string
          maxLength: 15
        dateOfBirth:
          type: string
          format: date
        mood:
          type: string
          maxLength: 100
        emergencyContact:
          type: string
          maxLength: 15
        healthPoints:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        doctor:
          type: integer
          nullable: true
      required:
      - dateOfBirth
      - email
      - emergencyContact
      - healthPoints
      - id
      - mood
      - name
      - phoneNumber
      - surname
    StateEnum:
      enum:
      - pending
      - confirmed
      - cancelled
      - completed
      type: string
      description: |-
        * `pending` - Pending
        * `confirmed` - Confirmed
        * `cancelled` - Cancelled
        * `completed` - Completed
    TypeEnum:
      enum:
      - inPerson
      - online
      type: string
      description: |-
        * `inPerson` - In Person
        * `online` - Online
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
