# Generated by Django 5.2 on 2025-04-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healtrack_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='ubication',
            new_name='localization',
        ),
    ]
