# Generated by Django 5.2 on 2025-05-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healtrack_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dateOfBirth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emergencyContact',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='healthPoints',
            new_name='health_points',
        ),
    ]
