# Generated by Django 5.2 on 2025-04-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healtrack_backend', '0002_rename_ubication_appointment_localization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='localization',
            new_name='location',
        ),
    ]
