# Generated by Django 5.2 on 2025-05-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtrack_backend', '0002_rename_dateofbirth_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='healtrack_backend.doctor'),
        ),
    ]
